/*
 * openZinkBooth
 * Copyright (C) 2026 olie.xdev <olie.xdeveloper@googlemail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

package com.photo.openzinkbooth.ui.theme

import androidx.compose.ui.graphics.Color

// ---------------------------------------------------------------------------
// Color scheme derived from the app icon brand color #156080.
// Generated following M3 tonal palette guidelines.
// ---------------------------------------------------------------------------

// ── Light theme ──────────────────────────────────────────────────────────────
val primaryLight                      = Color(0xFF156080)  // brand color
val onPrimaryLight                    = Color(0xFFFFFFFF)
val primaryContainerLight             = Color(0xFFBDE9FF)  // light tint
val onPrimaryContainerLight           = Color(0xFF001F2A)
val secondaryLight                    = Color(0xFF4D616C)
val onSecondaryLight                  = Color(0xFFFFFFFF)
val secondaryContainerLight           = Color(0xFFD0E6F2)
val onSecondaryContainerLight         = Color(0xFF081E27)
val tertiaryLight                     = Color(0xFF5C5B7E)
val onTertiaryLight                   = Color(0xFFFFFFFF)
val tertiaryContainerLight            = Color(0xFFE3DFFF)
val onTertiaryContainerLight          = Color(0xFF181837)
val errorLight                        = Color(0xFFBA1A1A)
val onErrorLight                      = Color(0xFFFFFFFF)
val errorContainerLight               = Color(0xFFFFDAD6)
val onErrorContainerLight             = Color(0xFF93000A)
val backgroundLight                   = Color(0xFFF5FAFE)
val onBackgroundLight                 = Color(0xFF171C1F)
val surfaceLight                      = Color(0xFFF5FAFE)
val onSurfaceLight                    = Color(0xFF171C1F)
val surfaceVariantLight               = Color(0xFFDBE4EA)
val onSurfaceVariantLight             = Color(0xFF3F484D)
val outlineLight                      = Color(0xFF6F787D)
val outlineVariantLight               = Color(0xFFBFC8CE)
val scrimLight                        = Color(0xFF000000)
val inverseSurfaceLight               = Color(0xFF2B3134)
val inverseOnSurfaceLight             = Color(0xFFECF1F5)
val inversePrimaryLight               = Color(0xFF87D1F0)
val surfaceDimLight                   = Color(0xFFD5DADE)
val surfaceBrightLight                = Color(0xFFF5FAFE)
val surfaceContainerLowestLight       = Color(0xFFFFFFFF)
val surfaceContainerLowLight          = Color(0xFFEFF4F8)
val surfaceContainerLight             = Color(0xFFE9EEF2)
val surfaceContainerHighLight         = Color(0xFFE3E8EC)
val surfaceContainerHighestLight      = Color(0xFFDDE2E7)

// Medium contrast light
val primaryLightMediumContrast        = Color(0xFF004E68)
val onPrimaryLightMediumContrast      = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast    = Color(0xFF2A7090)
val onPrimaryContainerLightMediumContrast  = Color(0xFFFFFFFF)
val secondaryLightMediumContrast      = Color(0xFF2D4450)
val onSecondaryLightMediumContrast    = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast  = Color(0xFF5B6F7B)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast       = Color(0xFF393860)
val onTertiaryLightMediumContrast     = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast   = Color(0xFF6B698E)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast          = Color(0xFF740006)
val onErrorLightMediumContrast        = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast    = Color(0xFFFFFFFF)
val backgroundLightMediumContrast     = Color(0xFFF5FAFE)
val onBackgroundLightMediumContrast   = Color(0xFF171C1F)
val surfaceLightMediumContrast        = Color(0xFFF5FAFE)
val onSurfaceLightMediumContrast      = Color(0xFF0C1215)
val surfaceVariantLightMediumContrast = Color(0xFFDBE4EA)
val onSurfaceVariantLightMediumContrast    = Color(0xFF2E373C)
val outlineLightMediumContrast        = Color(0xFF4A5358)
val outlineVariantLightMediumContrast = Color(0xFF656E73)
val scrimLightMediumContrast          = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2B3134)
val inverseOnSurfaceLightMediumContrast    = Color(0xFFECF1F5)
val inversePrimaryLightMediumContrast = Color(0xFF87D1F0)
val surfaceDimLightMediumContrast     = Color(0xFFC1C6CA)
val surfaceBrightLightMediumContrast  = Color(0xFFF5FAFE)
val surfaceContainerLowestLightMediumContrast  = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast     = Color(0xFFEFF4F8)
val surfaceContainerLightMediumContrast        = Color(0xFFE3E8EC)
val surfaceContainerHighLightMediumContrast    = Color(0xFFD7DCE0)
val surfaceContainerHighestLightMediumContrast = Color(0xFFCBD0D4)

// High contrast light
val primaryLightHighContrast          = Color(0xFF002F40)
val onPrimaryLightHighContrast        = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF00516B)
val onPrimaryContainerLightHighContrast    = Color(0xFFFFFFFF)
val secondaryLightHighContrast        = Color(0xFF192C38)
val onSecondaryLightHighContrast      = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast    = Color(0xFF354E58)
val onSecondaryContainerLightHighContrast  = Color(0xFFFFFFFF)
val tertiaryLightHighContrast         = Color(0xFF292845)
val onTertiaryLightHighContrast       = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast     = Color(0xFF464363)
val onTertiaryContainerLightHighContrast   = Color(0xFFFFFFFF)
val errorLightHighContrast            = Color(0xFF600004)
val onErrorLightHighContrast          = Color(0xFFFFFFFF)
val errorContainerLightHighContrast   = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast       = Color(0xFFF5FAFE)
val onBackgroundLightHighContrast     = Color(0xFF171C1F)
val surfaceLightHighContrast          = Color(0xFFF5FAFE)
val onSurfaceLightHighContrast        = Color(0xFF000000)
val surfaceVariantLightHighContrast   = Color(0xFFDBE4EA)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast          = Color(0xFF242C31)
val outlineVariantLightHighContrast   = Color(0xFF40484D)
val scrimLightHighContrast            = Color(0xFF000000)
val inverseSurfaceLightHighContrast   = Color(0xFF2B3134)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast   = Color(0xFF87D1F0)
val surfaceDimLightHighContrast       = Color(0xFFB3B8BC)
val surfaceBrightLightHighContrast    = Color(0xFFF5FAFE)
val surfaceContainerLowestLightHighContrast  = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast     = Color(0xFFECF1F5)
val surfaceContainerLightHighContrast        = Color(0xFFDDE2E7)
val surfaceContainerHighLightHighContrast    = Color(0xFFCFD4D8)
val surfaceContainerHighestLightHighContrast = Color(0xFFC1C6CA)

// ── Dark theme ───────────────────────────────────────────────────────────────
val primaryDark                       = Color(0xFF87D1F0)  // light tint of brand on dark
val onPrimaryDark                     = Color(0xFF003446)
val primaryContainerDark              = Color(0xFF004A62)
val onPrimaryContainerDark            = Color(0xFFBDE9FF)
val secondaryDark                     = Color(0xFFB4CAD6)
val onSecondaryDark                   = Color(0xFF1E333C)
val secondaryContainerDark            = Color(0xFF354E58)
val onSecondaryContainerDark          = Color(0xFFD0E6F2)
val tertiaryDark                      = Color(0xFFC5C3EA)
val onTertiaryDark                    = Color(0xFF2D2C4D)
val tertiaryContainerDark             = Color(0xFF444365)
val onTertiaryContainerDark           = Color(0xFFE3DFFF)
val errorDark                         = Color(0xFFFFB4AB)
val onErrorDark                       = Color(0xFF690005)
val errorContainerDark                = Color(0xFF93000A)
val onErrorContainerDark              = Color(0xFFFFDAD6)
val backgroundDark                    = Color(0xFF0E1417)
val onBackgroundDark                  = Color(0xFFDEE3E7)
val surfaceDark                       = Color(0xFF0E1417)
val onSurfaceDark                     = Color(0xFFDEE3E7)
val surfaceVariantDark                = Color(0xFF3F484D)
val onSurfaceVariantDark              = Color(0xFFBFC8CE)
val outlineDark                       = Color(0xFF899298)
val outlineVariantDark                = Color(0xFF3F484D)
val scrimDark                         = Color(0xFF000000)
val inverseSurfaceDark                = Color(0xFFDEE3E7)
val inverseOnSurfaceDark              = Color(0xFF2B3134)
val inversePrimaryDark                = Color(0xFF156080)
val surfaceDimDark                    = Color(0xFF0E1417)
val surfaceBrightDark                 = Color(0xFF343A3D)
val surfaceContainerLowestDark        = Color(0xFF090E11)
val surfaceContainerLowDark           = Color(0xFF171C1F)
val surfaceContainerDark              = Color(0xFF1B2023)
val surfaceContainerHighDark          = Color(0xFF252A2D)
val surfaceContainerHighestDark       = Color(0xFF303538)

// Medium contrast dark
val primaryDarkMediumContrast         = Color(0xFFB2E5FF)
val onPrimaryDarkMediumContrast       = Color(0xFF00273A)
val primaryContainerDarkMediumContrast     = Color(0xFF569AB7)
val onPrimaryContainerDarkMediumContrast   = Color(0xFF000000)
val secondaryDarkMediumContrast       = Color(0xFFC9DFEB)
val onSecondaryDarkMediumContrast     = Color(0xFF132630)
val secondaryContainerDarkMediumContrast   = Color(0xFF7E939F)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast        = Color(0xFFDCD9FF)
val onTertiaryDarkMediumContrast      = Color(0xFF222140)
val tertiaryContainerDarkMediumContrast    = Color(0xFF8F8DB3)
val onTertiaryContainerDarkMediumContrast  = Color(0xFF000000)
val errorDarkMediumContrast           = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast         = Color(0xFF540003)
val errorContainerDarkMediumContrast  = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast     = Color(0xFF000000)
val backgroundDarkMediumContrast      = Color(0xFF0E1417)
val onBackgroundDarkMediumContrast    = Color(0xFFDEE3E7)
val surfaceDarkMediumContrast         = Color(0xFF0E1417)
val onSurfaceDarkMediumContrast       = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast  = Color(0xFF3F484D)
val onSurfaceVariantDarkMediumContrast     = Color(0xFFD4DCE3)
val outlineDarkMediumContrast         = Color(0xFFAAB2B8)
val outlineVariantDarkMediumContrast  = Color(0xFF889096)
val scrimDarkMediumContrast           = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast  = Color(0xFFDEE3E7)
val inverseOnSurfaceDarkMediumContrast     = Color(0xFF25292D)
val inversePrimaryDarkMediumContrast  = Color(0xFF004A63)
val surfaceDimDarkMediumContrast      = Color(0xFF0E1417)
val surfaceBrightDarkMediumContrast   = Color(0xFF3F4548)
val surfaceContainerLowestDarkMediumContrast  = Color(0xFF03080B)
val surfaceContainerLowDarkMediumContrast     = Color(0xFF181D20)
val surfaceContainerDarkMediumContrast        = Color(0xFF23272B)
val surfaceContainerHighDarkMediumContrast    = Color(0xFF2D3235)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF383D40)

// High contrast dark
val primaryDarkHighContrast           = Color(0xFFDFF3FF)
val onPrimaryDarkHighContrast         = Color(0xFF000000)
val primaryContainerDarkHighContrast  = Color(0xFF87CEEC)
val onPrimaryContainerDarkHighContrast     = Color(0xFF000D16)
val secondaryDarkHighContrast         = Color(0xFFDDF3FF)
val onSecondaryDarkHighContrast       = Color(0xFF000000)
val secondaryContainerDarkHighContrast     = Color(0xFFB0C6D2)
val onSecondaryContainerDarkHighContrast   = Color(0xFF000D16)
val tertiaryDarkHighContrast          = Color(0xFFF1EEFF)
val onTertiaryDarkHighContrast        = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFC1BFE7)
val onTertiaryContainerDarkHighContrast    = Color(0xFF090625)
val errorDarkHighContrast             = Color(0xFFFFECE9)
val onErrorDarkHighContrast           = Color(0xFF000000)
val errorContainerDarkHighContrast    = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast  = Color(0xFF220001)
val backgroundDarkHighContrast        = Color(0xFF0E1417)
val onBackgroundDarkHighContrast      = Color(0xFFDEE3E7)
val surfaceDarkHighContrast           = Color(0xFF0E1417)
val onSurfaceDarkHighContrast         = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast    = Color(0xFF3F484D)
val onSurfaceVariantDarkHighContrast  = Color(0xFFFFFFFF)
val outlineDarkHighContrast           = Color(0xFFE8EFF5)
val outlineVariantDarkHighContrast    = Color(0xFFBAC2C8)
val scrimDarkHighContrast             = Color(0xFF000000)
val inverseSurfaceDarkHighContrast    = Color(0xFFDEE3E7)
val inverseOnSurfaceDarkHighContrast  = Color(0xFF000000)
val inversePrimaryDarkHighContrast    = Color(0xFF004A63)
val surfaceDimDarkHighContrast        = Color(0xFF0E1417)
val surfaceBrightDarkHighContrast     = Color(0xFF4B5053)
val surfaceContainerLowestDarkHighContrast  = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast     = Color(0xFF1B2023)
val surfaceContainerDarkHighContrast        = Color(0xFF2B3134)
val surfaceContainerHighDarkHighContrast    = Color(0xFF363B3F)
val surfaceContainerHighestDarkHighContrast = Color(0xFF42464A)